ODS.COUNTRYREGION (
    COUNTRYREGIONCODE VARCHAR2(2),
    NAME VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.EMPLOYEEDEPARTMENTHISTORY (
    BUSINESSENTITYID NUMBER,
    DEPARTMENTID NUMBER,
    SHIFTID NUMBER,
    STARTDATE DATE,
    ENDDATE DATE,
    MODIFIEDDATE DATE
);

ODS.EMPLOYEE (
    BUSINESSENTITYID NUMBER,
    NATIONALIDNUMBER NUMBER,
    LOGINID VARCHAR2(50),
    ORGANIZATIONNODE VARCHAR2(20),
    ORGANIZATIONLEVEL NUMBER,
    JOBTITLE VARCHAR2(50),
    BIRTHDATE DATE,
    MARITALSTATUS VARCHAR2(1),
    GENDER VARCHAR2(1),
    HIREDATE DATE,
    SALARIEDFLAG NUMBER,
    VACATIONHOURS NUMBER,
    SICKLEAVEHOURS NUMBER,
    CURRENTFLAG NUMBER,
    ROWGUID VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.PRODUCTCATEGORY (
    PRODUCTCATEGORYID NUMBER,
    NAME VARCHAR2(50),
    ROWGUID VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.DEPARTMENT (
    DEPARTMENTID NUMBER,
    NAME VARCHAR2(50),
    GROUPNAME VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.PRODUCTSUBCATEGORY (
    PRODUCTSUBCATEGORYID NUMBER,
    PRODUCTCATEGORYID NUMBER,
    NAME VARCHAR2(50),
    ROWGUID VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.STATEPROVINCE (
    STATEPROVINCEID NUMBER,
    STATEPROVINCECODE VARCHAR2(3),
    COUNTRYREGIONCODE VARCHAR2(2),
    ISONLYSTATEPROVINCEFLAG NUMBER,
    NAME VARCHAR2(50),
    TERRITORYID NUMBER,
    ROWGUID VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.PRODUCT (
    PRODUCTID NUMBER,
    NAME VARCHAR2(50),
    PRODUCTNUMBER VARCHAR2(50),
    MAKEFLAG NUMBER,
    FINISHEDGOODSFLAG NUMBER,
    COLOR VARCHAR2(10),
    SAFETYSTOCKLEVEL NUMBER,
    REORDERPOINT NUMBER,
    STANDARDCOST NUMBER,
    LISTPRICE NUMBER,
    SIZE VARCHAR2(10),
    SIZEUNITMEASURECODE VARCHAR2(3),
    WEIGHTUNITMEASURECODE VARCHAR2(3),
    WEIGHT FLOAT,
    DAYSTOMANUFACTURE NUMBER,
    PRODUCTLINE VARCHAR2(3),
    CLASS VARCHAR2(3),
    STYLE VARCHAR2(3),
    PRODUCTSUBCATEGORYID NUMBER,
    PRODUCTMODELID NUMBER,
    SELLSTARTDATE DATE,
    SELLENDDATE DATE,
    DISCONTINUEDDATE DATE,
    ROWGUID VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.EMPLOYEEPAYHISTORY (
    BUSINESSENTITYID NUMBER,
    RATECHANGEDATE DATE,
    RATE NUMBER,
    PAYFREQUENCY NUMBER,
    MODIFIEDDATE DATE
);

ODS.BUSINESSENTITYADDRESS (
    BUSINESSENTITYID NUMBER,
    ADDRESSID NUMBER,
    ADDRESSTYPEID NUMBER,
    ROWGUID VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.PERSONPHONE (
    BUSINESSENTITYID NUMBER,
    PHONENUMBER VARCHAR2(25),
    PHONENUMBERTYPEID NUMBER,
    MODIFIEDDATE DATE
);

ODS.BUSINESSENTITY (
    BUSINESSENTITYID NUMBER,
    ROWGUID VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.EMAILADDRESS (
    BUSINESSENTITYID NUMBER,
    EMAILADDRESSID NUMBER,
    EMAILADDRESS VARCHAR2(50),
    ROWGUID VARCHAR2(50),
    MODIFIEDDATE DATE
);

ODS.ADDRESS (
    ADDRESSID NUMBER,
    ADDRESSLINE1 VARCHAR2(255),
    ADDRESSLINE2 VARCHAR2(255),
    CITY VARCHAR2(20),
    STATEPROVINCEID NUMBER,
    POSTALCODE VARCHAR2(7),
    SPATIALLOCATION VARCHAR2(46),
    ROWGUID VARCHAR2(36),
    MODIFIEDDATE DATE
);

ODS.PERSON (
    BUSINESSENTITYID DATE,
    PERSONTYPE VARCHAR2(2),
    NAMESTYLE DATE,
    TITLE VARCHAR2(3),
    FIRSTNAME VARCHAR2(9),
    MIDDLENAME VARCHAR2(7),
    LASTNAME VARCHAR2(17),
    SUFFIX VARCHAR2(3),
    EMAILPROMOTION DATE,
    ADDITIONALCONTACTINFO VARCHAR2(3),
    DEMOGRAPHICS VARCHAR2(163),
    ROWGUID VARCHAR2(36),
    MODIFIEDDATE DATE
);

ALTER TABLE ODS.EMPLOYEEDEPARTMENTHISTORY ADD CONSTRAINT PK_EMPLOYEEDEPARTMENTHISTORY PRIMARY KEY (BUSINESSENTITYID);
ALTER TABLE ODS.EMPLOYEEDEPARTMENTHISTORY ADD CONSTRAINT FK_EMPLOYEEDEPARTMENTHISTORY_DEPARTMENT FOREIGN KEY (DEPARTMENTID) REFERENCES ODS.DEPARTMENT(DEPARTMENTID);

ALTER TABLE ODS.EMPLOYEE ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY (BUSINESSENTITYID);

ALTER TABLE ODS.PRODUCTCATEGORY ADD CONSTRAINT PK_PRODUCTCATEGORY PRIMARY KEY (PRODUCTCATEGORYID);

ALTER TABLE ODS.DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENTID);

ALTER TABLE ODS.PRODUCTSUBCATEGORY ADD CONSTRAINT PK_PRODUCTSUBCATEGORY PRIMARY KEY (PRODUCTSUBCATEGORYID);
ALTER TABLE ODS.PRODUCTSUBCATEGORY ADD CONSTRAINT FK_PRODUCTSUBCATEGORY_PRODUCTCATEGORY FOREIGN KEY (PRODUCTCATEGORYID) REFERENCES ODS.PRODUCTCATEGORY(PRODUCTCATEGORYID);

ALTER TABLE ODS.STATEPROVINCE ADD CONSTRAINT PK_STATEPROVINCE PRIMARY KEY (STATEPROVINCEID);

ALTER TABLE ODS.PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCTID);
ALTER TABLE ODS.PRODUCT ADD CONSTRAINT FK_PRODUCT_PRODUCTSUBCATEGORY FOREIGN KEY (PRODUCTSUBCATEGORYID) REFERENCES ODS.PRODUCTSUBCATEGORY(PRODUCTSUBCATEGORYID);

ALTER TABLE ODS.EMPLOYEEPAYHISTORY ADD CONSTRAINT PK_EMPLOYEEPAYHISTORY PRIMARY KEY (BUSINESSENTITYID);

ALTER TABLE ODS.BUSINESSENTITYADDRESS ADD CONSTRAINT PK_BUSINESSENTITYADDRESS PRIMARY KEY (BUSINESSENTITYID);
ALTER TABLE ODS.BUSINESSENTITYADDRESS ADD CONSTRAINT FK_BUSINESSENTITYADDRESS_ADDRESS FOREIGN KEY (ADDRESSID) REFERENCES ODS.ADDRESS(ADDRESSID);

ALTER TABLE ODS.PERSONPHONE ADD CONSTRAINT PK_PERSONPHONE PRIMARY KEY (BUSINESSENTITYID);

ALTER TABLE ODS.BUSINESSENTITY ADD CONSTRAINT PK_BUSINESSENTITY PRIMARY KEY (BUSINESSENTITYID);

ALTER TABLE ODS.EMAILADDRESS ADD CONSTRAINT PK_EMAILADDRESS PRIMARY KEY (BUSINESSENTITYID);
ALTER TABLE ODS.EMAILADDRESS ADD CONSTRAINT FK_EMAILADDRESS_EMAILADDRESS FOREIGN KEY (EMAILADDRESSID) REFERENCES ODS.EMAILADDRESS(EMAILADDRESSID);

ALTER TABLE ODS.ADDRESS ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDRESSID);
ALTER TABLE ODS.ADDRESS ADD CONSTRAINT FK_ADDRESS_STATEPROVINCE FOREIGN KEY (STATEPROVINCEID) REFERENCES ODS.STATEPROVINCE(STATEPROVINCEID);

ALTER TABLE ODS.PERSON ADD CONSTRAINT PK_PERSON PRIMARY KEY (BUSINESSENTITYID);

